# Generated by Django 5.0.4 on 2024-10-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CORE", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTP_For_UserRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("OTP_Email", models.CharField(blank=True, max_length=500, null=True)),
                ("OTP_Value", models.IntegerField()),
                ("OTP_Entered_Count", models.IntegerField()),
                (
                    "OTP_Status",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("OTP_Created_Date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "OTP FOR User Registration",
                "verbose_name_plural": "OTP FOR User Registration",
            },
        ),
    ]
