# Generated by Django 5.0.4 on 2024-10-15 07:24

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BulkEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_receipient_list",
                    models.FileField(upload_to="receipient_list"),
                ),
                ("email_subject", models.TextField()),
                ("email_message", ckeditor.fields.RichTextField()),
                ("email_status", models.TextField()),
                ("email_sending_date", models.DateTimeField(auto_now=True)),
                ("emails_sent_count", models.IntegerField(default=0)),
                ("email_pause_threshold", models.IntegerField(default=5)),
            ],
            options={
                "verbose_name_plural": "Bulk Email",
            },
        ),
        migrations.CreateModel(
            name="category_list",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=100)),
                ("updated_On", models.DateField(default=django.utils.timezone.now)),
                ("Last_Updated_On", models.DateField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "category_list",
            },
        ),
        migrations.CreateModel(
            name="language_list",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_name", models.CharField(max_length=25)),
                ("updated_On", models.DateField(default=django.utils.timezone.now)),
                ("Last_Updated_On", models.DateField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "language_list",
            },
        ),
        migrations.CreateModel(
            name="BulkEmailAttachments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="email_attachment"
                    ),
                ),
                (
                    "bulk_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.bulkemail",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Bulk Email Attachment",
            },
        ),
        migrations.CreateModel(
            name="English_Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department_name", models.TextField()),
                ("domain_name", models.CharField(max_length=256)),
                ("updated_On", models.DateField(default=django.utils.timezone.now)),
                ("Last_Updated_On", models.DateField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.category_list",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "English_Domain",
            },
        ),
        migrations.CreateModel(
            name="URL_dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("IDN_domain", models.CharField(max_length=255, unique=True)),
                ("ssl_configuration_status", models.TextField()),
                ("idn_domain_running_status", models.TextField()),
                ("content_language", models.TextField()),
                ("updated_On", models.DateField(default=django.utils.timezone.now)),
                ("Last_Updated_On", models.DateField(auto_now=True)),
                ("Remark", models.TextField()),
                (
                    "English_domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.english_domain",
                    ),
                ),
                (
                    "Language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.language_list",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "URL_dashboard",
            },
        ),
    ]
