# Generated by Django 5.0.4 on 2024-10-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Test", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Test",
            },
        ),
    ]
