# Generated by Django 4.1.7 on 2024-04-22 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic_name", models.CharField(max_length=255, unique=True)),
                ("creation_date", models.DateField(auto_now_add=True)),
                ("topic_slug", models.SlugField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Topic",
                "verbose_name_plural": "Topics",
            },
        ),
        migrations.CreateModel(
            name="TopicCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("creation_date", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Topic Category",
                "verbose_name_plural": "Topic Categories",
            },
        ),
        migrations.CreateModel(
            name="TopicAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.TextField(blank=True, null=True)),
                ("reply_date", models.DateField(auto_now_add=True)),
                (
                    "topic_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discussion_forum.topic",
                        verbose_name="Topic",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Topic Answer",
                "verbose_name_plural": "Topic Answers",
            },
        ),
        migrations.AddField(
            model_name="topic",
            name="topic_categories",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="discussion_forum.topiccategory",
                verbose_name="Topic Categories",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.CreateModel(
            name="AnswerUserReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UPVOTE", "UPVOTE"),
                            ("DOWNVOTE", "DOWNVOTE"),
                            ("NULL", "NULL"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("reply_date", models.DateField(auto_now_add=True)),
                (
                    "answer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discussion_forum.topicanswer",
                        verbose_name="Topic Answer",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Review On Answer",
                "verbose_name_plural": "User Review On Answer",
            },
        ),
        migrations.CreateModel(
            name="AnswerReplies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reply", models.TextField(blank=True, null=True)),
                ("reply_date", models.DateField(auto_now_add=True)),
                (
                    "answer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discussion_forum.topicanswer",
                        verbose_name="Topic Answer",
                    ),
                ),
                (
                    "replied_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discussion_forum.answerreplies",
                        verbose_name="replied to",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Answer Replies",
                "verbose_name_plural": "Answer Replies",
            },
        ),
    ]
